In [1]:
import pandas as pd

data = pd.read_excel("data/labels/nsd_coco.xlsx")

,Unnamed: 0,cocoId,cocoSplit,nsdId,file_name,amount_participants,subject
30935,30935,354095,train2017,30935,train2017/000000354095.jpg,8,NaN

In [2]:
data[
                data["cocoId"] == 354095
            ]

,Unnamed: 0,cocoId,cocoSplit,nsdId,file_name,amount_participants,subject
30935,30935,354095,train2017,30935,train2017/000000354095.jpg,8,NaN